# Generated by Django 3.2.13 on 2022-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='geography',
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
