# Generated by Django 3.2.13 on 2022-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contact',
            field=models.CharField(max_length=40),
        ),
    ]
