# Generated by Django 3.2.13 on 2022-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221106_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active_day',
            field=models.CharField(max_length=30),
        ),
    ]
