# Generated by Django 3.2.13 on 2022-11-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='homepage',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
