# Generated by Django 3.2.13 on 2022-11-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20221106_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='local',
            field=models.IntegerField(choices=[(1, '경기도'), (2, '강원도'), (3, '충청도'), (4, '경상도'), (5, '전라도'), (6, '제주도')], default=1),
            preserve_default=False,
        ),
    ]
