<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-11-02 09:38
=======


>>>>>>> dfd69c8d94737bb79483659c84f6dc64d18bbde1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('reviews', '0001_initial'),
        ('articles', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
=======

        ('articles', '0001_initial'),
        ('reviews', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),

>>>>>>> dfd69c8d94737bb79483659c84f6dc64d18bbde1
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(related_name='like_it', to='reviews.Review'),
        ),
        migrations.AddField(
            model_name='user',
            name='marker',
            field=models.ManyToManyField(related_name='articles', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
