# Generated by Django 3.2.13 on 2022-11-08 04:22


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('articles', '0001_initial'),
        ('accounts', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_articles',
            field=models.ManyToManyField(related_name='articles_like', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(related_name='reviews_like', to='reviews.Review'),
        ),
        migrations.AddField(
            model_name='user',
            name='marker',
            field=models.ManyToManyField(related_name='link_article', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
