# Generated by Django 3.2.13 on 2022-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221104_1609'),
        ('articles', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_articles',
            field=models.ManyToManyField(related_name='articles_like', to='reviews.Review'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(related_name='reviews_like', to='reviews.Review'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marker',
            field=models.ManyToManyField(related_name='link_article', to='articles.Article'),
        ),
    ]
