# Generated by Django 3.2.13 on 2022-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('accounts', '0002_alter_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.ManyToManyField(related_name='articles', to='articles.Article'),
        ),
    ]
