# Generated by Django 3.2.13 on 2022-11-03 09:58

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), accounts.models.input_only_number]),
        ),
    ]
