# Generated by Django 3.2.13 on 2022-11-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bookmark',
            new_name='marker',
        ),
    ]
