# Generated by Django 3.2.13 on 2022-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('accounts', '0003_auto_20221104_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_articles',
            field=models.ManyToManyField(related_name='articles_like', to='articles.Article'),
        ),
    ]
