# Generated by Django 3.2.13 on 2022-11-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('accounts', '0004_rename_bookmark_user_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(related_name='like_it', to='reviews.Review'),
        ),
    ]
