# Generated by Django 3.2.13 on 2022-11-04 16:09

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '#별 보기 좋은'), (2, '#시원한 여름'), (3, '#파티가 있는'), (4, '#가족이랑'), (5, '#커플'), (6, '#조용한'), (7, '#애견동반'), (8, '#도심 속 캠핑장'), (9, '#풍경이 좋은'), (10, '#2030인기'), (11, '#바다가 보이는')], max_length=23),
        ),
    ]
